from __future__ import annotations

import struct
from pathlib import Path

APP_NAME = "Safe Media Transfer"
PROTOCOL_VERSION = 1
FRAME_MAGIC = b"SMT1"

MESSAGE_TYPE_HELLO = 1
MESSAGE_TYPE_HELLO_ACK = 2
MESSAGE_TYPE_AUTH_REQUEST = 3
MESSAGE_TYPE_AUTH_RESULT = 4
MESSAGE_TYPE_MANIFEST = 5
MESSAGE_TYPE_MANIFEST_RESULT = 6
MESSAGE_TYPE_FILE_START = 7
MESSAGE_TYPE_FILE_RESUME_INFO = 8
MESSAGE_TYPE_FILE_CHUNK = 9
MESSAGE_TYPE_FILE_COMPLETE = 10
MESSAGE_TYPE_FILE_HASH_RESULT = 11
MESSAGE_TYPE_FILE_SKIP = 12
MESSAGE_TYPE_ERROR = 13
MESSAGE_TYPE_HEARTBEAT = 14
MESSAGE_TYPE_TRANSFER_COMPLETE = 15
MESSAGE_TYPE_CANCEL = 16

MESSAGE_TYPE_NAME_MAP = {
    MESSAGE_TYPE_HELLO: "HELLO",
    MESSAGE_TYPE_HELLO_ACK: "HELLO_ACK",
    MESSAGE_TYPE_AUTH_REQUEST: "AUTH_REQUEST",
    MESSAGE_TYPE_AUTH_RESULT: "AUTH_RESULT",
    MESSAGE_TYPE_MANIFEST: "MANIFEST",
    MESSAGE_TYPE_MANIFEST_RESULT: "MANIFEST_RESULT",
    MESSAGE_TYPE_FILE_START: "FILE_START",
    MESSAGE_TYPE_FILE_RESUME_INFO: "FILE_RESUME_INFO",
    MESSAGE_TYPE_FILE_CHUNK: "FILE_CHUNK",
    MESSAGE_TYPE_FILE_COMPLETE: "FILE_COMPLETE",
    MESSAGE_TYPE_FILE_HASH_RESULT: "FILE_HASH_RESULT",
    MESSAGE_TYPE_FILE_SKIP: "FILE_SKIP",
    MESSAGE_TYPE_ERROR: "ERROR",
    MESSAGE_TYPE_HEARTBEAT: "HEARTBEAT",
    MESSAGE_TYPE_TRANSFER_COMPLETE: "TRANSFER_COMPLETE",
    MESSAGE_TYPE_CANCEL: "CANCEL",
}

MESSAGE_NAME_TYPE_MAP = {name: code for code, name in MESSAGE_TYPE_NAME_MAP.items()}

DEFAULT_CHUNK_SIZE = 8 * 1024 * 1024
MIN_CHUNK_SIZE = 1 * 1024 * 1024
MAX_CHUNK_SIZE = 32 * 1024 * 1024

DEFAULT_PORT = 48555
MAX_CONTROL_MESSAGE_BYTES = 1 * 1024 * 1024
MAX_MANIFEST_BYTES = 32 * 1024 * 1024
MAX_FILE_COUNT = 100_000
MAX_PATH_UTF8_BYTES = 4096

DEFAULT_LOG_MAX_BYTES = 5 * 1024 * 1024
DEFAULT_LOG_BACKUP_COUNT = 10

DEFAULT_STAGING_SUFFIX = ".part"
DEFAULT_STATE_SUFFIX = ".part.json"

FRAME_HEADER_FORMAT = "!4sHHHQ16s"
FRAME_HEADER_SIZE = struct.calcsize(FRAME_HEADER_FORMAT)

WINDOWS_RESERVED_NAMES = {
    "CON", "PRN", "AUX", "NUL",
    "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9",
    "LPT1", "LPT2", "LPT3", "LPT4", "LPT5", "LPT6", "LPT7", "LPT8", "LPT9",
}

DEFAULT_ALLOWED_IMAGE_EXTENSIONS = {
    ".jpg", ".jpeg", ".png", ".heic", ".pdf",
}

DEFAULT_ALLOWED_VIDEO_EXTENSIONS = {
    ".mp4", ".mkv", ".mov", ".avi", ".mp3",
}

DEFAULT_BLOCKED_EXTENSIONS = {
    ".exe", ".msi", ".dll", ".sys", ".bat", ".cmd", ".com",
    ".ps1", ".py", ".js", ".vbs", ".sh", ".jar",
    ".lnk", ".url",
    ".zip", ".rar", ".7z", ".iso", ".tar", ".gz",
}

ROOT_DIR = Path(__file__).resolve().parent.parent